import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header";
import { Quicksand } from "next/font/google";
import SmoothScroll from "@/components/smooth-scroll";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} font-sans`}>
        <SmoothScroll>
        <Header />
        {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
